### ISSUE TITLE
Create a windows package!

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/utilities#1]
@rsignell-usgs conda win64 is in the oven...

**Comment by rsignell-usgs** [comment]
via AppVeyor?

**Comment by ocefpaf** [comment]
I wasn't planning to use AppVeyor (even though AppVeyor would be the best choice).  `utilities` has zero build dependencies (python only), but virtually our whole package stack as run dependencies!

    - iris
    - lxml
    - numpy
    - scipy
    - python
    - pandas
    - folium
    - oceans
    - netcdf4
    - pyugrid
    - matplotlib
    - beautifulsoup4
    - ipython-notebook

Building all that under windows just to run conda import test is a huge effort.  I was planning a regular pure python package at PyPI, that can be installed with pip.  Or maybe I could "cheat" and hide the import test when building a conda package?  Not sure...

**Comment by ocefpaf** [comment]
I am unable to build the latest owslib on windows.  The build fails trying to import `owslib.coverage`.  I will investigate further before reporting.  Anyways, for most of the notebooks here owslib > 0.8.9 **is** [broken](https://github.com/geopython/OWSLib/issues/218) and we have to use the latest checkout (or < 0.8.9).

Meanwhile I built the stable 0.8.7.

**Comment by rsignell-usgs** [comment]
Just to make sure I understand:
1) `owslib <= 0.8.7` or `owslib > 0.8.12` is required to run all our IOOS notebooks
2) only `owslib <= 0.8.7` is currently building as a conda package on windows

**Comment by rsignell-usgs** [comment]
When I try to build `utilities` as a package on anaconda win64, I get:
```
number of files: 17
BUILD END: utilities-0.0.1-np19py27_0
TEST START: utilities-0.0.1-np19py27_0
Fetching package metadata: ..........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[2/2                 ] |#################################################| 100%
Hint: utilities 0.0.1 np19py27_0 has a conflict with the remaining packages
```

**Comment by ocefpaf** [comment]
> Just to make sure I understand:
> 1) owslib <= 0.8.7 or owslib > 0.8.12 is required to run all our IOOS notebooks

Yes

2) only owslib <= 0.8.7 is currently building as a conda package on windows

Not anymore, see https://github.com/ioos/conda-recipes/pull/41

> Hint: utilities 0.0.1 np19py27_0 has a conflict with the remaining packages

Having similar issues here.  I will try to add a few lazy imports and see if I can get around that.  (Conda is biting today...)

**Comment by rsignell-usgs** [comment]
@ocefpaf , so that latest OWSLib from Master works?
Should I build this as OWSLib 0.8.13DEV or should we just ask Tom to cut a release?

**Comment by ocefpaf** [comment]
IMHO the bug introduced [here](https://github.com/geopython/OWSLib/pull/220/files) broke OWSLib and a (fast) bugfix release is needed.

**Comment by ocefpaf** [comment]
I was able to build win32 package,

https://binstar.org/ocefpaf/utilities/files

Now I get the same error message (`has a conflict with the remaining packages`) when tying to install it.  I guess that this is a mismatch with scitools windows packages (I am using their channel) and my own.  I will get back to this issue at a later time.

**Comment by ocefpaf** [comment]
The package is building on PR https://github.com/ioos/conda-recipes/pull/103.  Somehow it was not uploaded to binstar on the first try (https://github.com/ioos/conda-recipes/pull/94).
