### ISSUE TITLE
Possible bug in fes_date_filter

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/utilities#12]
@rsignell-usgs we are currently defining a fes date filter like this:

```python
def fes_date_filter(start, stop, constraint='overlaps'):
    start = start.strftime('%Y-%m-%d %H:00')
    stop = stop.strftime('%Y-%m-%d %H:00')
    if constraint == 'overlaps':
        propertyname = 'apiso:TempExtent_begin'
        begin = fes.PropertyIsLessThanOrEqualTo(propertyname=propertyname,
                                                literal=stop)
        propertyname = 'apiso:TempExtent_end'
        end = fes.PropertyIsGreaterThanOrEqualTo(propertyname=propertyname,
                                                 literal=start)
    elif constraint == 'within':
        propertyname = 'apiso:TempExtent_begin'
        begin = fes.PropertyIsGreaterThanOrEqualTo(propertyname=propertyname,
                                                   literal=start)
        propertyname = 'apiso:TempExtent_end'
        end = fes.PropertyIsLessThanOrEqualTo(propertyname=propertyname,
                                              literal=stop)
    else:
        raise NameError('Unrecognized constraint {}'.format(constraint))
    return begin, end
```

As I am writing docs and tests I found out that we get the following result from the function above:
```python
from datetime import datetime, timedelta
stop = datetime(2010, 1, 1, 12, 30, 59).replace(tzinfo=pytz.utc)
start = stop - timedelta(days=7)
begin, end = fes_date_filter(start, stop, constraint='overlaps')
begin.literal, end.literal
('2010-01-01 12:00', '2009-12-25 12:00')

begin.propertyoperator, end.propertyoperator
('ogc:PropertyIsLessThanOrEqualTo', 'ogc:PropertyIsGreaterThanOrEqualTo')

begin, end = fes_date_filter(start, stop, constraint='within')
begin.literal, end.literal
('2009-12-25 12:00', '2010-01-01 12:00')

begin.propertyoperator, end.propertyoperator
('ogc:PropertyIsGreaterThanOrEqualTo', 'ogc:PropertyIsLessThanOrEqualTo')
```

My interpretation of `within` and `overlaps` is that the limits are **exclusive** and  **inclusive** (respectively).  Here they seem to be the same thing just reversed in the return order.

If I am correct, to fix this we should remove the reversion and change `PropertyIsLess(More)ThanOrEqualTo` to `PropertyIsLess(More)Than` in the `within` option.

Since you are the original author can you tell my if my interpretation is wrong or if this is really a bug?

**Comment by ocefpaf** [comment]
This function is used only for the `csw` search so, as long as the data exist in the filter in any condition, it will always be downloaded later.  That masked a few bugs!  I decided to go simple and create a version of `fes_date_filter()` that search from `start` to `stop` including both ends.
(See #82)

**Comment by rsignell-usgs** [comment]
I think the original logic is correct:
let's say the data range is `[d0, d1]`
and the user range is `[u0, u1].

The data `overlaps` when `[d0 <= u1 && d1 >=u0]`

**Comment by ocefpaf** [comment]
I guess we need more testing for this one!

Ping @rsignell-usgs
